=== astaputhra/fileSense/target/classes/uploadResource/UploadMappingGrammer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hexagon.in/UploadMappingGrammer"
	xmlns:umg="http://www.hexagon.in/UploadMappingGrammer"
	elementFormDefault="unqualified">

	<xs:element name="uploadMappings" type="umg:uploadMappingsForm"/>

	<xs:complexType name="uploadMappingsForm">
		<xs:sequence>
			<xs:element name="mappingDefinition"
				type="umg:mappingDefinitionForm"
				minOccurs="0"
				maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="mappingDefinitionForm">
		<xs:sequence>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="historyTableName"
				type="umg:historyTableNameForm"
				minOccurs="0"
				maxOccurs="1"/>
			<xs:element name="tableName" type="umg:tableNameForm"/>
			<xs:element name="additionalTables" type="xs:string"/>
            <xs:element name="postUploadClass"
                type="umg:postUploadClassForm"
                minOccurs="0"
                maxOccurs="1"/>
            <xs:element name="postUploadEvent"
                type="umg:postUploadEventForm"
                minOccurs="0"
                maxOccurs="1"/>
			<xs:element name="alternateProcess"
				type="umg:postUploadClassForm"
				minOccurs="0"
				maxOccurs="1"/>
			<xs:element name="alternateUploadEvent"
				type="umg:postUploadEventForm"
				minOccurs="0"
				maxOccurs="1"/>
            <xs:element name="roConverter"
                type="umg:roConverterForm"
                minOccurs="0"
                maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="postUploadClassForm">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9_.])*"/>
			<xs:whiteSpace value="collapse"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:simpleType name="postUploadEventForm">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9_.])*"/>
            <xs:whiteSpace value="collapse"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="roConverterFormForm">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9_.])*"/>
            <xs:whiteSpace value="collapse"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="historyTableNameForm">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9_])*"/>
			<xs:whiteSpace value="collapse"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tableNameForm">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9_])*"/>
			<xs:whiteSpace value="collapse"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== astaputhra/fileSense/target/classes/uploadResource/UploadTypeMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<umg:uploadMappings xmlns:umg="http://www.hexagon.in/UploadMappingGrammer"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.hexagon.in/UploadMappingGrammer UploadMappingGrammer.xsd">
    <!--<mappingDefinition>-->
        <!--<type>BRS Posting Control Upload</type>-->
        <!--<tableName>PORTFOLIO_SUBRED_UPD</tableName>-->
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.UpdPortfolioSubredProcess</postUploadClass>-->
        <!--<postUploadEvent>DummyUploadProcessEvent</postUploadEvent>-->
    <!--</mappingDefinition>-->

    <mappingDefinition>
        <type>Bank Statement</type>
        <tableName>UPD_BANK_STMT</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>BSENSE Collection Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>Bank Collection Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>HV Bank Collection</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>CMS Bank Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>SIP Bank Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>CAMSEPS Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>

    </mappingDefinition>

    <mappingDefinition>
        <type>Bank Collection Data Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>TECHPROCESS Collection Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>ONLINE Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>REFUND Collection Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>FNET Transactions</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>High Value Transaction</type>
        <tableName>UPD_MF_BANK_DATA</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.BankDataProcess</postUploadClass>-->
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>BRS Collection Transaction</type>
        <tableName>UPD_MF_COLLECTION</tableName>

        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>

        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.UpdMfCollectionProcess</postUploadClass>-->
        <!--<postUploadEvent>DummyUploadProcessEvent</postUploadEvent>-->
    </mappingDefinition>

    <!--<mappingDefinition>-->
    <!--<type>BRS Redemption Transaction</type>-->
    <!--<tableName>UPD_MF_REDEMPTION</tableName>-->
    <!--<postUploadClass>com.hexgen.brs.p1.core.components.datauploader.events.UpdMfRedemptionUploadedEvent</postUploadClass>-->
    <!--</mappingDefinition>-->

    <!--<mappingDefinition>-->
        <!--<type>Ledger Bank Transaction Opening Balance</type>-->
        <!--<tableName>UPD_LEDGER_ENTRY</tableName>-->
        <!--<postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.UpdLedgerEntryProcess</postUploadClass>-->
        <!--<postUploadEvent>DummyUploadProcessEvent</postUploadEvent>-->
    <!--</mappingDefinition>-->


    <mappingDefinition>
        <type>Ledger Balance</type>
        <tableName>UPD_LEDGER_BAL</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <!--<mappingDefinition>
        <type>Redemption Funding</type>
        <tableName>UPD_MF_FUNDING</tableName>
        <postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.UpdMfFundingProcess</postUploadClass>
        <postUploadEvent>DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>Brokerage Funding</type>
        <tableName>UPD_MFBRK_FUNDING</tableName>
        <postUploadClass>com.hexgen.p1.vert.externalfeedmgr.internal.UpdMfBrkFundingProcess</postUploadClass>
        <postUploadEvent>DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>-->

    <mappingDefinition>
        <type>Collection Refund</type>
        <tableName>UPD_MF_REFUND</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>Collection A3</type>
        <tableName>UPD_COLLECTION_ANNEX</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>Ins Bank Statement</type>
        <tableName>UPD_INS_BANK_STMT</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>Insurance Collection Register</type>
        <tableName>UPD_INS_COLLECTION</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>

    <mappingDefinition>
        <type>Insurance Disbursement Register</type>
        <tableName>UPD_INS_DISBURSE</tableName>
        <postUploadClass>com.iMatch.etl.dataupload.DefaultETLProcess</postUploadClass>
        <postUploadEvent>com.iMatch.etl.datauploader.DummyUploadProcessEvent</postUploadEvent>
    </mappingDefinition>
